import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import { getAuth, signInAnonymously } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import { getFirestore, doc, setDoc, updateDoc, getDoc, onSnapshot, collection, serverTimestamp, runTransaction } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";
import { firebaseConfig } from "./firebase-config.js";

const $=s=>document.querySelector(s), symbols={'+':'+','−':'−','×':'×','÷':'÷'};
const state={uid:null,role:null,roomId:null,room:null,privateNumber:null,selectedOp:'+',answer:null,roomStop:null,privateStop:null,countdownStarted:false};
const show=n=>{document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(`#${n}-screen`).classList.add('active')};
const configured=()=>!firebaseConfig.apiKey.startsWith("PASTE_");
if(!configured()){$('#loading-copy').textContent='Firebase has not been configured yet. Add your Firebase web app settings in firebase-config.js, then publish again.'} else start();

let db,auth;
async function start(){try{const app=initializeApp(firebaseConfig);db=getFirestore(app);auth=getAuth(app);const user=await signInAnonymously(auth);state.uid=user.user.uid;show('home')}catch(err){$('#loading-copy').textContent='Could not connect to the game service. Check Firebase setup and refresh.';console.error(err)}}
const roomRef=()=>doc(db,'rooms',state.roomId),privateRef=uid=>doc(db,'rooms',state.roomId,'privateNumbers',uid),answerRef=uid=>doc(db,'rooms',state.roomId,'answers',uid);
const code=()=>Array.from({length:5},()=> 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[Math.floor(Math.random()*32)]).join('');
const isHost=()=>state.role==='host',myIndex=()=>isHost()?0:1,chooser=room=>room.round%2===1?0:1;

$('#create-button').onclick=()=>show('create');$('#join-button').onclick=()=>show('join');
$('#create-form').onsubmit=async e=>{e.preventDefault();state.role='host';state.roomId=code();const name=$('#host-name').value.trim()||'Host',matchLength=+document.querySelector('input[name="match-length"]:checked').value;await setDoc(roomRef(),{hostUid:state.uid,hostName:name,guestUid:null,guestName:null,matchLength,status:'waiting',round:0,scores:[0,0],operation:null,hostLocked:false,guestLocked:false,equation:null,winner:null,createdAt:serverTimestamp()});watchRoom()};
$('#join-form').onsubmit=async e=>{e.preventDefault();state.role='guest';state.roomId=$('#join-code').value.trim().toUpperCase();const name=$('#guest-name').value.trim()||'Guest';try{await runTransaction(db,async tx=>{const snap=await tx.get(roomRef());if(!snap.exists())throw Error('Game not found.');const room=snap.data();if(room.guestUid)throw Error('This game already has two players.');tx.update(roomRef(),{guestUid:state.uid,guestName:name,status:'choosing',round:1});});watchRoom()}catch(err){$('#join-error').textContent=err.message||'Could not join that game.';state.roomId=null}};
function watchRoom(){state.roomStop?.();state.roomStop=onSnapshot(roomRef(),snap=>{if(!snap.exists())return;state.room=snap.data();render()})}
function render(){const r=state.room;if(!r)return;$('#game-code').textContent=state.roomId;$('#player-list').replaceChildren(...[[r.hostName,'Host'],[r.guestName,'Player 2']].filter(([n])=>n).map(([n,role])=>{const d=document.createElement('div');d.textContent=`${role} · ${n}`;return d}));if(r.status==='waiting'){show('lobby');return} if(r.status==='choosing')return renderOperation();if(r.status==='selecting')return renderNumbers();if(r.status==='reveal'||r.status==='countdown'||r.status==='playing')return renderGame();if(r.status==='result')return renderResult()}
function renderOperation(){const mine=myIndex()===chooser(state.room);$('#operation-eyebrow').textContent=`Round ${state.room.round} · ${[state.room.hostName,state.room.guestName][chooser(state.room)]} chooses`;$('#operation-title').textContent=mine?'Choose an operation.':`${[state.room.hostName,state.room.guestName][chooser(state.room)]} is choosing.`;$('#operation-copy').textContent=mine?'You control this round’s operation.':'Operation choice alternates every round.';$('#operation-grid').style.display=mine?'grid':'none';$('#lock-operation').style.display=mine?'block':'none';show('operation')}
document.querySelectorAll('.operation').forEach(b=>b.onclick=()=>{document.querySelector('.operation.selected').classList.remove('selected');b.classList.add('selected');state.selectedOp=b.dataset.operation});
$('#lock-operation').onclick=()=>updateDoc(roomRef(),{operation:state.selectedOp,status:'selecting',hostLocked:false,guestLocked:false,equation:null,winner:null});
function renderNumbers(){const r=state.room,locked=isHost()?r.hostLocked:r.guestLocked;if(locked){show('waiting');return}$('#number-eyebrow').textContent=`Round ${r.round} · ${symbols[r.operation]} selected`;$('#my-number').value='';$('#number-error').textContent='';show('number')}
$('#number-form').onsubmit=async e=>{e.preventDefault();const value=+$('#my-number').value;if(!Number.isInteger(value)||value<1||value>99)return $('#number-error').textContent='Choose a whole number from 1 to 99.';state.privateNumber=value;await setDoc(privateRef(state.uid),{value,round:state.room.round});await updateDoc(roomRef(),isHost()?{hostLocked:true}:{guestLocked:true});};
async function revealIfReady(){const r=state.room;if(!isHost()||r.status!=='selecting'||!r.hostLocked||!r.guestLocked)return;await updateDoc(roomRef(),{status:'reveal'});const [a,b]=await Promise.all([getDoc(privateRef(r.hostUid)),getDoc(privateRef(r.guestUid))]).then(x=>x.map(s=>s.data().value));if(r.operation==='÷'&&a%b){await updateDoc(roomRef(),{hostLocked:false,guestLocked:false,status:'selecting'});return}await updateDoc(roomRef(),{equation:{a,b,op:r.operation},status:'countdown',countdownAt:Date.now()+3000})}
function renderGame(){const r=state.room;if(r.status==='reveal')return void revealIfReady();if(!r.equation)return;const q=r.equation;state.answer={'+':q.a+q.b,'−':q.a-q.b,'×':q.a*q.b,'÷':q.a/q.b}[q.op];$('#equation').textContent=`${q.a} ${symbols[q.op]} ${q.b}`;$('#score-name-one').textContent=r.hostName;$('#score-name-two').textContent=r.guestName;$('#score-one').textContent=r.scores[0];$('#score-two').textContent=r.scores[1];$('#round-label').textContent=`Round ${r.round}`;$('#round-count').textContent=`${r.round} / ${r.matchLength}`;show('game');if(r.status==='countdown')runCountdown(r.countdownAt);else enableAnswers()}
function runCountdown(at){if(state.countdownStarted)return;state.countdownStarted=true;const tick=()=>{const remaining=Math.max(0,Math.ceil((at-Date.now())/1000));$('#countdown').textContent=remaining||'GO!';$('#countdown').classList.add('show');if(remaining>0)return setTimeout(tick,180);setTimeout(()=>{state.countdownStarted=false;$('#countdown').classList.remove('show');if(isHost())updateDoc(roomRef(),{status:'playing'});},300)};tick()}
function enableAnswers(){$('#game-message').textContent='First correct answer scores';if(state.room.winner!==null){$('#answer-input').disabled=true;$('#answer-form button').disabled=true;return}$('#answer-input').disabled=false;$('#answer-form button').disabled=false}
$('#answer-form').onsubmit=async e=>{e.preventDefault();const value=+$('#answer-input').value;if(!Number.isFinite(value)||state.room.winner!==null)return;if(value!==state.answer){$('#answer-input').value='';$('#game-message').textContent='Not quite — keep trying!';return}$('#answer-input').disabled=true;$('#answer-form button').disabled=true;if(isHost())award(0);else await setDoc(answerRef(state.uid),{value,round:state.room.round,submittedAt:Date.now()})};
async function award(winner){const r=state.room;if(r.winner!==null)return;const scores=[...r.scores];scores[winner]++;await updateDoc(roomRef(),{scores,winner,status:'playing'});setTimeout(async()=>{const latest=(await getDoc(roomRef())).data();if(latest.round>=latest.matchLength){await updateDoc(roomRef(),{status:'result'});return}await updateDoc(roomRef(),{round:latest.round+1,status:'choosing',operation:null,equation:null,winner:null})},1500)}
function renderResult(){const r=state.room,[a,b]=r.scores,winner=a===b?null:a>b?0:1;$('#result-title').textContent=winner===null?'A perfect draw.':'A winner emerges.';$('#result-copy').textContent=winner===null?`It is a draw after ${r.matchLength} rounds.`:`${[r.hostName,r.guestName][winner]} wins the match!`;$('#final-score').textContent=`${r.hostName}  ${a} – ${b}  ${r.guestName}`;show('result')}
setInterval(async()=>{if(!state.room||!isHost())return;if(state.room.status==='selecting')await revealIfReady();if(state.room.status==='playing'&&state.room.winner===null){const answers=await getDoc(answerRef(state.room.guestUid));if(answers.exists()&&answers.data().round===state.room.round&&answers.data().value===state.answer)await award(1)}},350);
