const $=s=>document.querySelector(s),channel=new BroadcastChannel('math-clash-local-test');
const state={role:null,gameId:null,names:[],matchLength:3,round:0,scores:[0,0],operation:'+',numbers:[null,null],answer:0,hostWaiting:false,accepting:false,resolved:false};
const sym={'+':'+','−':'−','×':'×','÷':'÷'},show=n=>{document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(`#${n}-screen`).classList.add('active')},send=(type,data={})=>channel.postMessage({type,gameId:state.gameId,...data}),host=()=>state.role==='host',mine=()=>host()?0:1,turn=()=>state.round%2===1?0:1;
const code=()=>Array.from({length:5},()=> 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[Math.floor(Math.random()*32)]).join('');
$('#create-button').onclick=()=>show('create');$('#join-button').onclick=()=>show('join');
$('#create-form').onsubmit=e=>{e.preventDefault();state.role='host';state.gameId=code();state.names=[$('#host-name').value.trim()||'Host',''];state.matchLength=+document.querySelector('input[name="match-length"]:checked').value;renderLobby();show('lobby');state.hostWaiting=true;announce()};
$('#join-form').onsubmit=e=>{e.preventDefault();state.role='guest';state.gameId=$('#join-code').value.trim().toUpperCase();state.names=['',$('#guest-name').value.trim()||'Guest'];$('#join-error').textContent='Looking for that game…';send('join',{name:state.names[1]});setTimeout(()=>{if(!state.names[0])$('#join-error').textContent='Game not found. Check the code and ask the host to keep the lobby open.'},1400)};
function announce(){if(!state.hostWaiting)return;send('open',{hostName:state.names[0],matchLength:state.matchLength});setTimeout(announce,700)}
function renderLobby(){$('#game-code').textContent=state.gameId;$('#lobby-status').textContent=state.names[1]?'Both players are here. Starting the first round…':'Waiting for another player to join…';$('#player-list').replaceChildren(...state.names.filter(Boolean).map((n,i)=>{const d=document.createElement('div');d.textContent=`${i?'Player 2':'Host'} · ${n}`;return d}))}
function start(){state.hostWaiting=false;state.round=1;state.scores=[0,0];if(host())send('start',{names:state.names,matchLength:state.matchLength});setTimeout(begin,650)}
function begin(){state.operation='+';state.numbers=[null,null];state.resolved=false;const choose=mine()===turn();$('#turn-eyebrow').textContent=`Round ${state.round} · ${state.names[turn()]} chooses`;$('#turn-title').textContent=choose?'Choose an operation.':`${state.names[turn()]} is choosing.`;$('#turn-intro').textContent=choose?'You control this round’s operation.':'Operations alternate every round.';$('#operation-grid').style.display=choose?'grid':'none';$('#confirm-operation').style.display=choose?'block':'none';show('turn')}
document.querySelectorAll('.operation').forEach(b=>b.onclick=()=>{document.querySelector('.operation.selected').classList.remove('selected');b.classList.add('selected');state.operation=b.dataset.operation});
$('#confirm-operation').onclick=()=>{send('operation',{operation:state.operation});pick(state.operation)};
function pick(op){state.operation=op;$('#number-eyebrow').textContent=`Round ${state.round} · ${sym[op]} selected`;$('#number-intro').textContent=op==='÷'?'Choose a number from 1–99. Clean division is enforced once both numbers are revealed.':'Only you can see this input. Your number stays hidden until both players lock theirs.';$('#my-number').value='';$('#number-error').textContent='';show('number')}
$('#number-form').onsubmit=e=>{e.preventDefault();const val=+$('#my-number').value;if(!Number.isInteger(val)||val<1||val>99)return $('#number-error').textContent='Choose a whole number from 1 to 99.';state.numbers[mine()]=val;send('number',{player:mine(),value:val});show('waiting');if(state.numbers.every(Number.isInteger)&&host())reveal()};
function reveal(){const[a,b]=state.numbers;if(state.operation==='÷'&&a%b){send('redo');return}state.answer={'+':a+b,'−':a-b,'×':a*b,'÷':a/b}[state.operation];send('reveal',{numbers:state.numbers,operation:state.operation,answer:state.answer});countdown()}
function countdown(){$('#equation').textContent=`${state.numbers[0]} ${sym[state.operation]} ${state.numbers[1]}`;score();$('#round-label').textContent=`Round ${state.round}`;$('#round-count').textContent=`${state.round} / ${state.matchLength}`;$('#game-message').textContent='Memorize the equation';$('#answer-input').value='';$('#answer-input').disabled=true;$('#answer-form button').disabled=true;show('game');let t=3;$('#countdown').textContent=t;$('#countdown').classList.add('show');const id=setInterval(()=>{t--,$('#countdown').textContent=t||'GO!';if(t<=0){clearInterval(id);setTimeout(()=>{$('#countdown').classList.remove('show');$('#game-message').textContent='First correct answer scores';state.accepting=true;$('#answer-input').disabled=false;$('#answer-form button').disabled=false;$('#answer-input').focus()},300)}},1000)}
$('#answer-form').onsubmit=e=>{e.preventDefault();if(!state.accepting||state.resolved)return;const v=+$('#answer-input').value;if(v===state.answer){if(host())won(mine());else send('answer',{player:mine(),value:v});$('#answer-input').disabled=true;$('#answer-form button').disabled=true}else{$('#answer-input').value='';$('#game-message').textContent='Not quite — keep trying!'}};
function score(){$('#score-name-one').textContent=state.names[0];$('#score-name-two').textContent=state.names[1];$('#score-one').textContent=state.scores[0];$('#score-two').textContent=state.scores[1]}
function won(p){if(state.resolved)return;state.resolved=true;state.accepting=false;state.scores[p]++;score();$('#game-message').textContent=`${state.names[p]} is fastest!`;if(host())send('won',{player:p});setTimeout(()=>{if(state.round>=state.matchLength)finish();else{state.round++;begin()}},1500)}
function finish(){const[a,b]=state.scores;$('#result-title').textContent=a===b?'A perfect draw.':'A winner emerges.';$('#result-copy').textContent=a===b?`It is a draw after ${state.matchLength} rounds.`:`${state.names[a>b?0:1]} wins the match!`;const f=$('#final-score'),l=document.createElement('span'),r=document.createElement('strong'),q=document.createElement('span');l.textContent=state.names[0];r.textContent=`${a} – ${b}`;q.textContent=state.names[1];f.replaceChildren(l,r,q);show('result')}
channel.onmessage=({data:d})=>{if(d.gameId!==state.gameId)return;if(d.type==='open'&&!host()){state.names[0]=d.hostName;state.matchLength=d.matchLength;$('#join-error').textContent='';send('join',{name:state.names[1]})}if(d.type==='join'&&host()&&!state.names[1]){state.names[1]=d.name;send('joined',{names:state.names,matchLength:state.matchLength});renderLobby();start()}if(d.type==='joined'&&!host()){state.names=d.names;state.matchLength=d.matchLength;renderLobby();show('lobby')}if(d.type==='start'&&!host()){state.names=d.names;state.matchLength=d.matchLength;setTimeout(begin,650)}if(d.type==='operation')pick(d.operation);if(d.type==='number'){state.numbers[d.player]=d.value;if(host()&&state.numbers.every(Number.isInteger))reveal()}if(d.type==='redo'){state.numbers=[null,null];$('#number-error').textContent='Those numbers do not divide evenly. Choose another number.';show('number')}if(d.type==='reveal'){state.numbers=d.numbers;state.operation=d.operation;state.answer=d.answer;countdown()}if(d.type==='answer'&&host()&&d.value===state.answer)won(d.player);if(d.type==='won'&&!host())won(d.player)};
